name: book
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - statsmodels
  - matplotlib
  - seaborn
  - ghp-import
  - gdown
  - jupyter-book
  - ffmpeg
  - pip:
    - myst_nb